# Generated by Django 5.2.12 on 2026-04-19 11:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_remove_bill_updated_at_remove_bill_utility_type_and_more'),
        ('providers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='billing_month',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='bill',
            unique_together={('user', 'service', 'billing_month')},
        ),
    ]
